<?php

namespace FondOfSpryker\Zed\JellyfishSalesOrder\Dependency\Service;

use FondOfSpryker\Zed\Jellyfish\Dependency\Service\JellyfishToUtilEncodingServiceBridge as FondOfSprykerJellyfishToUtilEncodingServiceBridge;

class JellyfishSalesOrderToUtilEncodingServiceBridge extends FondOfSprykerJellyfishToUtilEncodingServiceBridge implements JellyfishSalesOrderToUtilEncodingServiceInterface
{
}
